services:
  - type: web
    name: sogang-reborn
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true 